config/routes.rb
Project2Rails::Application.routes.draw do

	get 'registrants' => 'registrants#index' #list all
	get 'registrants/:id' => 'registrants#show' #show one
	post 'registrants' => 'registrants#create' #create a new one
	put 'registrants/:id' => 'registrants#update' #edit a current one
	patch 'registrants/:id' => 'registrants#update' #edit a current one
	delete 'registrants/:id' => 'registrants#delete' #delete a current one



	# Session
	get "login" => "session#new"
	post "login" => "session#create"
	delete "logout" => "session#destroy"
	get "logout" => "session#destroy"

	# Registration
	get "register/:code" => "registration#new"
	post "register/:code" => "registration#create"
	
	# Password reset
	get "reset/:code" => "password#edit"
	put "reset/:code" => "password#update"
	patch "reset/:code" => "password#update"


	get "privacy" => "site#privacy"
	get "terms" => "site#terms"

	root 'site#index'

end

app/models/registrant.rb
class Registrant
	include Mongoid::Document
	include Mongoid::Timestamps

	field :id, type: String
	field :name, type: String
	field :email, type: String
	field :expires_at, type: Time
end

app/models/user.rb
class User
	include Mongoid::Document
	include Mongoid::Timestamps

	attr_accessor :password, :password_confirmation 

	field :id, type: String
	field :name, type: String
	field :email, type: String
	field :expires_at, type: Time
	field :code, type: String
	field :fish, type: String
	field :salt, type: String

	before_save :encrypt_password

	private

	def encrypt_password
		if password.present?
			self.salt = BCrypt::Engine.generate_salt
			self.fish = BCrypt::Engine.hash_secret(password, self.salt)
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController	
	def edit
	end

	def update
	end

end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController	
	def new
	end

	def create
	end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController	
	def new
	end

	def create
	end

	def destroy
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController	
	def index
		@users = User.all.entries
	end

	def privacy
	end

	def terms
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.slim
.navbar.navbar-inverse.navbar-fixed-top
	.container
		span.navbar-brand.logo ToddyCat

app/views/layouts/_navigation.html.slim
.navbar.navbar-inverse.navbar-fixed-top
	.container
		button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
		span.icon-bar
		span.icon-bar
		span.icon-bar
		= link_to_unless_current "ToddyCat, root_url, class: "navbar-brand logo" do 
			span.navbar-brand.logo ToddyCat
		.collapse.navbar-collapse
			ul.nav.navbar-nav.pull-right
				li
					=link_to "Sign out", logout_url, class: "logout-link"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project2Rails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.slim
doctype html
html lang="en"
head
  meta charset="utf-8"
  meta name= "viewport" content="width=device-width, initial scale=1.9"

    title ToddyCat

    = csrf_meta_tags

    = stylesheet_link_tag "application", media: "all"
  body
    #wrap
      == render partial: 'layouts/header'

      .container
        .page
          == yield

  #footer
    .container
      p.text-muted.credit
        =>link_to "Privacy Policy", privacy_url
        ' &bull;
        =>link_to "Terms of Use", terms_url
        ' &bull; &copy; 2013 ToddyCat


    = javascript_include_tag "application"

app/views/password/edit.html.slim
h1 Please retype your password

app/views/session/new.html.slim
h1 Please sign in

app/views/site/index.html.slim
.row
	.col-lg-6.col-lg-offset-3
		h1 Our Users
		table.table.table-bordered.table-striped
			thead
				tr
					th Name
					th Email
					th Created
			trbody
			- @users.each do |user|
				tr 
					th#{user.name}
					td#{user.email}
					td#{user.created_at}

app/views/site/privacy.html.slim
Privacy

app/views/site/terms.html.slim
Terms